// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpeioblwbyjzjoupspnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZWlvYmx3YnlqempvdXBzcG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MDcwMzAsImV4cCI6MjA1Njk4MzAzMH0.-abnyWG0pnQA4V4rDpuL-DYtTdWJomcR-3UvXmHAeQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);