// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlveydcydnkgrscfsaes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "52da3b3f5c748c9059e8ab9dddfcd55867dd593475cb06de5a8062a95e0d17a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);